### PR TITLE
fix: don't report error when using Builder<*>

### LINKED ISSUE #2074: Regression of Eloquent Query Builder where method
- Larastan Version: 2.9.9
- Laravel Version: 11.28.1

### Description
I'm getting the following error with my static analysis today:
```
  :51    Parameter #1 $column of method Illuminate\Database\Eloquent\Builder<*>::where() expects array<int|model property of never, mixed>|(Closure(Illuminate\Database\Eloquent\Builder<*>):  
         mixed)|Illuminate\Contracts\Database\Query\Expression|model property of never, 'record_status' given.   
```

Indicating that I'm sending an incorrect value to the where method. However I'm sending a simple string for the column name. See code below.

### Laravel code where the issue was found

```php
        $query = $this->getBasePinsQuery()
            ->where(static function (Builder $query) {
                $query->where('record_status', '!=', Pin::RECORD_STATUS_ACTIVE)
                    ->orWhereNull('record_status');
            })
            ->whereNull('deleted_at')
            ->whereRaw("to_tsvector('simple', public.f_concat_ws(' ', address, city, state, zip))
                @@ plainto_tsquery('simple', ?)", $search);

        return $query->limit(20)->get();
```
The error refers to line 51, which is `$query->where('record_status', '!=', Pin::RECORD_STATUS_ACTIVE)`

However, if I replace the where that passes in the closure with a simple where as such:

```php
        $query = $this->getBasePinsQuery()
            ->where('record_status', '')
            ->whereNull('deleted_at')
            ->whereRaw("to_tsvector('simple', public.f_concat_ws(' ', address, city, state, zip))
                @@ plainto_tsquery('simple', ?)", $search);

        return $query->limit(20)->get();
```

I get the same error:

```
  :50    Parameter #1 $column of method Illuminate\Database\Eloquent\Builder<*>::where() expects array<int|model property of never, mixed>|(Closure(Illuminate\Database\Eloquent\Builder<*>):  
         mixed)|Illuminate\Contracts\Database\Query\Expression|model property of never, 'record_status' given. 
```

Line 50, which would be `->where('record_status', '')`

I downgraded larastan to 2.9.8 and it started working again, so the regression must be with this morning's release of 2.9.9

### PR DESCRIPTION
**Pull request by calebdw**
Hello!

This closes #2074

Thanks!

### CODE REVIEW

**Review by szepeviktor — APPROVED** [review]

File: src/Types/ModelProperty/GenericModelPropertyType.php [hunk 1]
```diff
@@ -65,7 +65,7 @@ public function acceptsWithReason(Type $type, bool $strictTypes): AcceptsResult
             }
 
             if (count($genericType->getObjectClassNames()) < 1) {
-                return AcceptsResult::createNo();
+                return AcceptsResult::createYes();
```
Comment (canvural) [inline src/Types/ModelProperty/GenericModelPropertyType.php:68]: Can we do a `maybe` here? Are the any negative impacts?

Comment (calebdw) [reply src/Types/ModelProperty/GenericModelPropertyType.php:68]: `maybe` results in the same error

**Comment by canvural** [comment]
Thank you!
