### PR TITLE
Resolve guard user from request

### LINKED ISSUE #1778: Incorrect user model resolved from Request object for non-default guard
- Larastan Version: 2.6.4
- `--level` used: 2
- Pull request with failing test:

### Description
Hello!

I'm trying to resolve a user from the `Illuminate\Http\Request` object (using `$request->user('internal')`), but Larastan thinks the user returned is from the default guard.

Note that the correct user model *is* returned when using the `Auth` facade (`Auth::guard('internal')->user()`).

Thanks!

### PR DESCRIPTION
**Pull request by calebdw**
- [x] Added or updated tests

Closes #1778

**Changes**

This PR updates the dynamic property extension for the `$request->user()` method to account for the guard passed in.

Thanks!

### CODE REVIEW

**Comment by fabriciojs** [comment]
👍🏻  needing this!

File: tests/Type/data/request-object.php [hunk 1]
```diff
@@ -14,5 +14,3 @@
 assertType('Illuminate\Routing\Route|null', $request->route());
 assertType('object|string|null', $request->route('foo'));
 assertType('object|string|null', $request->route('foo', 'bar'));
-
-assertType('App\User|null', $request->user());
```
Comment (canvural) [inline tests/Type/data/request-object.php:18]: Why was this removed?

**Review by canvural — CHANGES_REQUESTED** [review]
Hi,

Just left one question. Other than that it looks good 👍🏽

File: tests/Type/data/request-object.php (hunk 1 above)
Comment (calebdw) [reply tests/Type/data/request-object.php:18]: I moved it to be with the other `$request->user` tests:

image

**Comment by calebdw** [comment]
@canvural, I resolved the thread, please just let me know if you need anything else!

**Comment by calebdw** [comment]
@canvural

Sorry to bug! But I'm waiting on this PR so I can update my codebase to Level 2 without having to ignore a bunch of errors. Would it be possible to release this sometime this week? If not then no worries and I hope you have a Merry Christmas season!

Thanks!

**Comment by calebdw** [comment]
@canvural, I hope you had a happy new years!!

If there's nothing else holding up this PR can we get it merged and tagged please?

Thanks!!

**Comment by canvural** [comment]
Thank you!
