### PR TITLE
Fix UnusedViewsRule not providing an existing file path to RuleErrorBuilder

### LINKED ISSUE #1725: UnusedViewsRule does not pass an existing file path to RuleErrorBuilder
- Larastan Version: b49b6d3ec144c675fa86bbe453ef11d8c42c2016

### Description

The next version of PHPStan is going to require an existing file path to be passed to `RuleErrorBuilder::file()`. This prevents various issues with the baseline and result cache.

When I try this, Larastan test suite fails with:

```
1) Rules\UnusedViewsRuleTest::testRule
PHPStan\ShouldNotHappenException: File unused.blade.php does not exist.

phar:///Users/ondrej/Development/larastan/vendor/phpstan/phpstan/phpstan.phar/src/Rules/RuleErrorBuilder.php:56
/Users/ondrej/Development/larastan/src/Rules/UnusedViewsRule.php:75
phar:///Users/ondrej/Development/larastan/vendor/phpstan/phpstan/phpstan.phar/src/Testing/RuleTestCase.php:126
phar:///Users/ondrej/Development/larastan/vendor/phpstan/phpstan/phpstan.phar/src/Testing/RuleTestCase.php:86
/Users/ondrej/Development/larastan/tests/Rules/UnusedViewsRuleTest.php:50
```

That's because `$unusedViews` in UnusedViewsRule contains strings like `unused` and not paths to existing files.

### PR DESCRIPTION
**Pull request by mad-briller**
- [x] Added or updated tests
- [x] Documented user facing changes
 
closes https://github.com/larastan/larastan/issues/1725

**Changes**

The `UnusedViewsRule` now uses the `ViewFinderInterface` to specify the full path to the unused view, rather than the short name. This is to resolve a constraint with a future version of PHPStan that will require all `RuleErrorBuilder->file()` calls to be absolute paths to existing files.

**Breaking changes**

It's likely that any past baselines that were generated including an `UnusedViewsRule` violation will need regenerating as the reported path will change. Not alot we can do about that though as it's a necessary change for a future version of phpstan.

### CODE REVIEW

File: src/Rules/UnusedViewsRule.php [hunk 1]
```diff
@@ -5,6 +5,7 @@
 namespace Larastan\Larastan\Rules;
 
 use Illuminate\View\Factory;
+use Illuminate\View\ViewFinderInterface;
```
Comment (canvural) [inline src/Rules/UnusedViewsRule.php]: I don't see where this interface is used 🤔

Comment (mad-briller) [reply src/Rules/UnusedViewsRule.php]: my mistake, a holdover from an original approach before i learned that `->getFinder()` existed

**Comment by canvural** [comment]
Thank you!
