### PR TITLE
Fix not respecting return type of overridden Request::user() method.

### LINKED ISSUE #1718: Wrong return type when overwriting Request::user()
- Larastan Version: 2.6.4
- `--level` used: 8

### Description
Larastan will overwrite the return type of requests that narrow the return of `user()`.
```
  5     Cannot access property $id on App\User|null.
```

### Laravel code where the issue was found

```php
<?php

namespace App\Http\Requests;

resolve(AuthedRequest::class)->user()->id
```

```php
<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;
use App\User;

class AuthedRequest extends FormRequest
{
    public function authorize(): bool
    {
        return parent::user() instanceof User;
    }

    public function user($guard = null): User
    {
        $user = parent::user($guard);
        if (!$user instanceof User) {
            abort(403);
        }

        return $user;
    }
}
```

### PR DESCRIPTION
**Pull request by mad-briller**
- [x] Added or updated tests

closes https://github.com/larastan/larastan/issues/1718

**Changes**

Change RequestUserExtension to use the specific type of an overridden `Request::user()` method

### CODE REVIEW

File: tests/Type/GeneralTypeTest.php [hunk 1]
```diff
@@ -59,6 +59,7 @@ public static function dataFileAsserts(): iterable
         yield from self::gatherAssertTypes(__DIR__.'/data/view-exists.php');
         yield from self::gatherAssertTypes(__DIR__.'/data/view.php');
         yield from self::gatherAssertTypes(__DIR__.'/data/where-relation.php');
+        yield from self::gatherAssertTypes(__DIR__.'/data/bug-1718.php');
```
Comment (calebdw) [inline tests/Type/GeneralTypeTest.php]: I would put this with the other bugs

**Comment by calebdw** [comment]
You beat me to this!

File: src/ReturnTypes/RequestUserExtension.php [hunk 2]
```diff
@@ -48,6 +48,10 @@ public function getTypeFromMethodCall(
         MethodCall $methodCall,
         Scope $scope
     ): Type {
+        if ($methodReflection->getDeclaringClass()->getName() !== Request::class) {
+            return ParametersAcceptorSelector::selectSingle($methodReflection->getVariants())->getReturnType();
```
Comment (canvural) [inline src/ReturnTypes/RequestUserExtension.php]: Can't we return `null` here?

**Review by canvural — CHANGES_REQUESTED** [review]
Looks good. Thanks.

Just left a one comment. Also the branch has merge conflicts now. That's why it is a good idea to put any test case in `GeneralTypeTest` to at the end of the file. The order of the tests do not matter at all 😊

**Comment by calebdw** [comment]
> Also the branch has merge conflicts now. That's why it is a good idea to put any test case in GeneralTypeTest to at the end of the file. The order of the tests do not matter at all 😊

I get that order does not matter (other than for aesthetics), but you would still have merge conflicts if two separate PRs placed files in the same spot at the end of the file.

**Comment by mad-briller** [comment]
i'll get to this proper when i have some time after work

**Comment by HDVinnie** [comment]
Whats the status on this @mad-briller @calebdw @canvural

**Comment by szepeviktor** [comment]
This PR needs to be fixed.

**Comment by mad-briller** [comment]
not sure what's going on with CI, appears to be some stuff broken outside the scope of this pr, and that are failing on other recent prs too
but this pr should be ready now, sorry for the delay it slipped my mind

**Comment by calebdw** [comment]
Awesome thanks! Laravel 11 tests are broken until #1990 is merged and the other tests are failing due to PHPstan 1.12 which will be fixed with #2028

**Comment by canvural** [comment]
Thank you!
