### PR TITLE
fix: transform ide-helper relationship docblocks into typed collections

### LINKED ISSUE #476: Incorrect return type when accessing model's relationship property when using IDE helper
- Larastan Version: `dev-master`
- `--level` used: 5

### Description
When running larastan on a model file that has laravel-ide-helper docblocks committed, we run into errant generic return type issues.

### Laravel code where the issue was found

Here is a test case added to `Tests\Features\Models\Relations.php`

```php
/** @test */
    public function test_it_fails_with_ide_helper(): ?Account
    {
        $user = new User();

        return $user->accounts->first();
    }
```

This test passes, until docblocks generated by laravel-ide-helper are added to the `User.php` model.

```
/**
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Account[] $accounts
 */
```

```
./vendor/bin/phpstan analyse -c ./tests/phpstan-tests.neon --ansi --memory-limit=1G tests/Features/Models/Relations.php
 1/1 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

 ------ ------------------------------------------------------------------------------------------------------------
  Line   Relations.php
 ------ ------------------------------------------------------------------------------------------------------------
  149    Method Tests\Features\Models\Relations::test_it_fails_with_ide_helper() should return App\Account|null but
         returns Illuminate\Database\Eloquent\Model|null.
```

### Notes
This test case will pass if we typehint the collection being returned to be `@property-read \Illuminate\Database\Eloquent\Collection<\App\Account>|\App\Account[] $accounts`

Is there a way we can infer this automatically? Laravel-ide-helper is quite a common tool for most laravel developers.

### Workaround
use `@var` annotation

```php
/** @test */
    public function test_it_fails_with_ide_helper(): ?Account
    {
        $user = new User();
        
        /** @var \App\Account $account */
        $account = $user->accounts->first();
        return $account
    }
```

### PR DESCRIPTION
**Pull request by mr-feek**
fixes #476 

This is almost entirely @ondrejmirtes's code. It seems to work well for us and fixes the broken test.

### CODE REVIEW

File: src/Types/GenericEloquentCollectionTypeNodeResolverExtension.php [hunk 1]
```diff
@@ -0,0 +1,74 @@
...
+ *
+ * \Illuminate\Database\Eloquent\Collection<\App\Account> $accounts
+ *
+ * Now IDE's can benefit from auto-completion, and we can benefit from the correct type passed to the generic collection
+ */
+class GenericEloquentCollectionTypeNodeResolverExtension implements TypeNodeResolverExtension
+{
+    public function resolve(TypeNode $typeNode, NameScope $nameScope): ?Type
+    {
+        if ($typeNode instanceof UnionTypeNode && count($typeNode->types) === 2) {
```
Comment (szepeviktor) [inline src/Types/GenericEloquentCollectionTypeNodeResolverExtension.php]: Could you bail out here? `return null;`

Comment (mr-feek) [reply src/Types/GenericEloquentCollectionTypeNodeResolverExtension.php]: Sure, refactored to prefer short-circuiting and returning early, to remove a level of indentation 👍
