### PR TITLE
Return correct collection instance when calling all

### LINKED ISSUE #452: Collection doesn't return correct model instance
- Larastan Version: 0.5.1
- `--level` used: max

### Description
When getting the first value in a collection the return type is invalid. You get the error:
`testAllFirst() should return App\\User but returns Illuminate\\Database\\Eloquent\\Model|null.`

### Laravel code where the issue was found

```php
/**
* @return User
*/
public function testAllFirst(): User
{
    return User::all()->first();
}
```

### PR DESCRIPTION
**Pull request by BertvanHoekelen**
Fixes #452 

Calling `User::all();` returned a `Eloquent/Collection`. This PR makes sure a `Support/Collection` is returned so that `User::all()->first()` returns a `User|null`.

### CODE REVIEW

**Comment by szepeviktor** [comment]
Thank you for you PR!
https://www.php.net/manual/en/function.in-array.php
in_array return a boolean. Could you please correct the code?

**Comment by BertvanHoekelen** [comment]
@szepeviktor Done!

**Comment by szepeviktor** [comment]
Thanks.
Could you add a 3rd parameter `true` to get in_array work in a strict mode?

File: src/ReturnTypes/ModelExtension.php [hunk 1]
```diff
@@ -109,6 +110,10 @@ public function getTypeFromStaticMethodCall(
             $returnType = new GenericObjectType(EloquentBuilder::class, [new ObjectType($scope->resolveName($methodCall->class))]);
         }
 
+        if (in_array(Collection::class, $returnType->getReferencedClasses()) && $methodCall->name->name === 'all') {
+            $returnType = new IntersectionType([new ObjectType(\Illuminate\Support\Collection::class), $returnType->getTypes()[1]]);
```
Comment (canvural) [inline src/ReturnTypes/ModelExtension.php]: It should be the generic type here. `new GenericType(Collection::class, [new ObjectType()])`

File: tests/Features/Methods/ModelExtension.php [hunk 2]
```diff
@@ -13,13 +13,18 @@
 class ModelExtension
 {
     /**
-     * @return \Illuminate\Database\Eloquent\Collection<User>
+     * @return \Illuminate\Support\Collection<User>
```
Comment (canvural) [inline tests/Features/Methods/ModelExtension.php]: It was correct before. `all` returns `\Illuminate\Database\Eloquent\Collection` not ` \Illuminate\Support\Collection`

File: src/ReturnTypes/ModelExtension.php [hunk 3]
```diff
@@ -109,6 +110,10 @@ public function getTypeFromStaticMethodCall(
             $returnType = new GenericObjectType(EloquentBuilder::class, [new ObjectType($scope->resolveName($methodCall->class))]);
         }
 
+        if (in_array(Collection::class, $returnType->getReferencedClasses()) && $methodCall->name->name === 'all') {
```
Comment (canvural) [inline src/ReturnTypes/ModelExtension.php]: We should use `$methodReflection->getName()` instead of `$methodCall->name->name`

Also, can you check if we need to do this to methods other than `all` ?

Comment (BertvanHoekelen) [reply src/ReturnTypes/ModelExtension.php]: I think `all` is the only one that should be fixed in the `ModelExtension.php`. However when adding the test below it gives the same error. So maybe I'm working in the wrong file?

```php
public static function findFirstFooBarThread(): Thread
{
    return self::query()->where('foo', 'bar')->get()->first();
}
```

Comment (canvural) [reply src/ReturnTypes/ModelExtension.php]: That `get` call is on the builder not model. So let's make another issue/PR for that one.

Comment (BertvanHoekelen) [reply src/ReturnTypes/ModelExtension.php]: Will do!
