### PR TITLE
Fixed issue where collections with invalid templates configured would cause a fatal error.

### LINKED ISSUE #1565: Null given to ObjectType::isSuperTypeOf()
- Larastan Version: 2.4.1
- `--level` used: 8
- Pull request with failing test:

### Description

The use of `random()` results in:
```
Internal error: PHPStan\Type\ObjectType::isSuperTypeOf(): Argument #1 ($type) must be of type PHPStan\Type\Type, null given, called in                                          
     /vendor/nunomaduro/larastan/src/ReturnTypes/CollectionGenericStaticMethodDynamicMethodReturnTypeExtension.php on line 116
```

### Laravel code where the issue was found

```php
/** @var Brand $brand */
$brand = Brand::findOrFail(1);
$department = $brand->groups->random();
```
```php
/** @return BelongsToMany<UserGroup> */
public function groups(): BelongsToMany
{
  return $this->belongsToMany(
    UserGroup::class,
    BrandOperatorGroupMembership::class,
    'brand_id',
    'group_id'
  );
}
```

### PR DESCRIPTION
**Pull request by mad-briller**
- [x] Added or updated tests

closes https://github.com/larastan/larastan/issues/1565

**Changes**

Fixes a long standing issue where custom collections that don't specify `@extends` cause crashes when calling functions on them that are handled by `CollectionGenericStaticMethodDynamicMethodReturnTypeExtension`.

Comments in the report suggest adding a rule to enforce that collections always have `@extends` but this seems superfluous as phpstan already reports this at a sufficiently high level.

### CODE REVIEW

**Review by szepeviktor — APPROVED** [review]

File: tests/Type/GeneralTypeTest.php [hunk 1]
```diff
@@ -59,6 +59,7 @@ public static function dataFileAsserts(): iterable
         yield from self::gatherAssertTypes(__DIR__.'/data/view-exists.php');
         yield from self::gatherAssertTypes(__DIR__.'/data/view.php');
         yield from self::gatherAssertTypes(__DIR__.'/data/where-relation.php');
+        yield from self::gatherAssertTypes(__DIR__.'/data/bug-1565.php');
```
Comment (calebdw) [inline tests/Type/GeneralTypeTest.php]: I would move this up with the other bugs

File: tests/Type/data/bug-1565.php [hunk 2]
```diff
@@ -0,0 +1,30 @@
+<?php
+
+namespace Bug1565;
+
+use Illuminate\Support\Collection;
+
+use function PHPStan\Testing\assertType;
+
+class TestCollection extends Collection
```
Comment (calebdw) [inline tests/Type/data/bug-1565.php:9]: I would probably add a comment that the generics are specifically excluded.

Comment (calebdw) [reply tests/Type/data/bug-1565.php:9]: eh, nevermind---I missed that this was defined directly in the test file

**Comment by canvural** [comment]
Thank you!
