### PR TITLE
fix: array access on container

### LINKED ISSUE #429: Does Lumen have an internal error?
or are we unable to understand Lumen's code?

(recently in CI)
```
 ------ ---------------------------------------------- 

  Line   Providers/AuthServiceProvider.php             

 ------ ---------------------------------------------- 

  33     Offset 'auth' does not exist on               

         Illuminate\Contracts\Foundation\Application.  

 ------ ---------------------------------------------- 
```

https://github.com/laravel/lumen/blob/master/app/Providers/AuthServiceProvider.php#L33

### PR DESCRIPTION
**Pull request by canvural**
Fixes #429

### CODE REVIEW

File: tests/Features/ReturnTypes/ContainerArrayAccessTest.php [hunk 1]
```diff
@@ -0,0 +1,19 @@
...
+
+use Illuminate\Auth\AuthManager;
+use Illuminate\Contracts\Foundation\Application;
+
+class ContainerArrayAccessTest
+{
+    /** @var Application */
+    protected $app;
+
+    public function testAuth(): ?AuthManager
```
Comment (nunomaduro) [inline tests/Features/ReturnTypes/ContainerArrayAccessTest.php]: `auth` always exists on the container. I would prefer the test to be:

```
public function testAuth(): AuthManager
```

Comment (canvural) [reply tests/Features/ReturnTypes/ContainerArrayAccessTest.php]: It's because of [this](https://github.com/nunomaduro/larastan/blob/master/src/Properties/ReflectionTypeContainer.php#L43) line. I can change it to `false`. It doesn't seem to affect anything else. But not sure.

Comment (nunomaduro) [reply tests/Features/ReturnTypes/ContainerArrayAccessTest.php]: If that lines specifies what can be resolved out of the container, a null can't be relsolved I guess.

Comment (canvural) [reply tests/Features/ReturnTypes/ContainerArrayAccessTest.php]: Changed.

File: tests/Features/ReturnTypes/ContainerArrayAccessTest.php [hunk 2]
```diff
@@ -0,0 +1,19 @@
...
+
+use Illuminate\Auth\AuthManager;
+use Illuminate\Contracts\Foundation\Application;
+
+class ContainerArrayAccessTest
+{
+    /** @var Application */
+    protected $app;
+
+    public function testAuth(): AuthManager
```
Comment (nunomaduro) [inline tests/Features/ReturnTypes/ContainerArrayAccessTest.php]: Can you also add a test just bellow, that resolves $this->app['fooooooooo']; ? I am curious about the result.

Comment (canvural) [reply tests/Features/ReturnTypes/ContainerArrayAccessTest.php]: It would throw `BindingResolutionException` exception.

Comment (nunomaduro) [reply tests/Features/ReturnTypes/ContainerArrayAccessTest.php]: Don't merge this yet. I want to run some tests.
