### PR TITLE
fix: fixes query builder methods within custom builders

### LINKED ISSUE #352: Invalid "self" type for custom Builder
- Larastan Version: 0.4.3
- `--level` used: max

### Description
Based on https://timacdonald.me/dedicated-eloquent-model-query-builders/ I have converted most of my code base away from Model scopes to custom query builders. This made using them in an IDE a lot asier.

Problem is: Simple functions like
```php
public function whereActive(): self
{
  return $this->whereNotNull('accepted_at');
}
```
work as expected. The problem starts as soon as another "scope" gets called inside this builder:

### Laravel code where the issue was found
(just an example)

```php
class UserBuilder extends Builder {
  public function whereVerified(): self
  {
    return $this->whereNotNull('email_verified_at');
  }

  public function whereVip(): self
  {
    return $this->whereVerified()->where('points', '>', 50000);
  }
}
```

Since whereVerified() returns an instance of `self` this seems to overwrite the analysis and any consecute calls get the wrong scope. Even attaching PHPDocs like `@return \Illuminate\Database\Eloquent\Builder|self` don't work.

### PR DESCRIPTION
**Pull request by canvural**
Fixes #352 

Calling query builder methods inside the custom builder classes wasn't returning the generic builder. This PR fixes that.

### CODE REVIEW

File: tests/Features/ReturnTypes/CustomEloquentBuilderTest.php [hunk 1]
```diff
@@ -96,4 +101,15 @@ public function type(string $type): CustomBuilder
     {
         return $this->where(['type' => $type]);
     }
+
+    /**
+     * @param string[] $categories
+     *
+     * @return CustomBuilder
+     * @phpstan-return CustomBuilder<TModelClass>
```
Comment (szepeviktor) [inline tests/Features/ReturnTypes/CustomEloquentBuilderTest.php]: I think other phpdoc parsing software understand `CustomBuilder<TModelClass>`

File: src/Methods/EloquentBuilderForwardsCallsExtension.php [hunk 2]
```diff
@@ -88,18 +89,24 @@ public function getMethod(ClassReflection $classReflection, string $methodName):
...
         $modelType = $templateTypeMap->getType('TModelClass');
 
-        if ($this->getBuilderReflection()->hasNativeMethod($methodName) && ($modelType === null || ! $modelType instanceof ObjectType)) {
+        if ($this->getBuilderReflection()->hasNativeMethod($methodName) && (! $modelType instanceof ObjectType)) {
             $methodReflection = $this->getBuilderReflection()->getNativeMethod($methodName);
+            $builderClass = EloquentBuilder::class;
+
+            if ($modelType instanceof TemplateMixedType) {
+                /** @var string $builderClass */
+                $builderClass = $modelType->getScope()->getClassName();
```
Comment (szepeviktor) [inline src/Methods/EloquentBuilderForwardsCallsExtension.php]: Could class name be a non-string?

File: tests/Features/ReturnTypes/CustomEloquentBuilderTest.php (hunk 1 above)
Comment (canvural) [reply tests/Features/ReturnTypes/CustomEloquentBuilderTest.php]: PHPStorm was complaining about it for me.

File: src/Methods/EloquentBuilderForwardsCallsExtension.php (hunk 2 above)
Comment (canvural) [reply src/Methods/EloquentBuilderForwardsCallsExtension.php]: Yes. Technically it can be `null`. But in reality, it'll never be. So this comment is just to tell PHPStan that it's a string.

File: tests/Features/ReturnTypes/CustomEloquentBuilderTest.php (hunk 1 above)
Comment (szepeviktor) [reply tests/Features/ReturnTypes/CustomEloquentBuilderTest.php]: I see. Generics! https://plugins.jetbrains.com/plugin/12754-php-generics

File: src/Methods/EloquentBuilderForwardsCallsExtension.php (hunk 2 above)
Comment (szepeviktor) [reply src/Methods/EloquentBuilderForwardsCallsExtension.php]: Thanks.

File: tests/Features/ReturnTypes/CustomEloquentBuilderTest.php (hunk 1 above)
Comment (canvural) [reply tests/Features/ReturnTypes/CustomEloquentBuilderTest.php]: Oh, cool. But I don't want to install a plugin for that. PHPStorm will eventually support it.
